version: "3"
services:
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: password
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    api:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./app.js/:/app/app.js
            - ./src:/app/src
        ports:
            - "8080:8080"
        depends_on:
            - db
